# Generated by Django 2.1.2 on 2018-10-14 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('md5', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='running', max_length=10)),
            ],
        ),
    ]
